### PR TITLE
Feature/upgrade kotlin and gradle

### PR DESCRIPTION
**Pull request by geekbeast**
Please test this out on a phone just to make sure there are no breaking changes. 

- Upgrades to gradle7
- Upgrades to latest version of kotlin
- Removes deprecated library references
- Fixes linting error usage stats

### CODE REVIEW

**Comment by anzioka** [comment]
Screen Shot 2021-12-06 at 6 09 14 PM

**Comment by anzioka** [comment]
Unable to install app locally on any emulator:
```
Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: Error loading build artifacts from: /Users/alfoncenzioka/Projects/open2/android/chronicle/app/build/outputs/apk/debug/output-metadata.json
```

**Comment by geekbeast** [comment]
Do you have JDK11 installed?

**Comment by geekbeast** [comment]
I updated Bamboo to build with JDK 11.

**Comment by anzioka** [comment]
Tested on various android versions (21, 25, 27, 28, 29 and 30) and didn't notice any abnormalities

**Review by anzioka — APPROVED** [review]

**Review by UnsungHero97 — APPROVED** [review]

**Pull request merged**
